# Generated by Django 5.0.7 on 2024-07-28 17:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userEmail', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
            ],
        ),
    ]
