# Generated by Django 5.0.7 on 2024-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
