# Generated by Django 5.0.7 on 2024-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alert_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='created',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='userEmail',
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
