# Generated by Django 5.0.7 on 2024-07-28 18:09

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_alert_created_remove_alert_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='alert',
            name='firstName',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='lastName',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='alert',
            name='userEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
