# Generated by Django 5.0.7 on 2024-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_alert_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(default='CREATED', max_length=80),
        ),
    ]
