# Generated by Django 5.0.7 on 2024-07-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_alert_currentprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='firstName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='userEmail',
        ),
        migrations.AlterField(
            model_name='alert',
            name='currentPrice',
            field=models.FloatField(default=0),
        ),
    ]
